name: flutter_umeng_ushare
description: A flutter plugin for umeng u-share library, support wechat share, QQ/Tim share ...
version: 1.0.6
homepage: https://github.com/youyiio/flutter_umeng_ushare
publish_to: none

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.beyongx.flutter_umeng_ushare
        pluginClass: UmengUsharePlugin
      ios:
        pluginClass: UmengUsharePlugin
  